name: Build & release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
        
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get dependencies
        run: go get -v -t -d ./...
      
    #   - name: Test
    #     run: go test -v ./...
        
      - name: Build for Linux
        run: go build -v -o github-markdown-stars-updater-linux-amd64
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
          GO111MODULE: on
      
      - name: Build for Windows
        run: go build -v -o github-markdown-stars-updater-windows-amd64.exe
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
          GO111MODULE: on
            
      - name: Build for MacOS (AMD64)
        run: go build -v -o github-markdown-stars-updater-darwin-amd64
        env:
          GOOS: darwin
          GOARCH: amd64
          CGO_ENABLED: 0
          GO111MODULE: on
      
      - name: Build for MacOS (ARM64)
        run: go build -v -o github-markdown-stars-updater-darwin-arm64
        env:
          GOOS: darwin
          GOARCH: arm64
          CGO_ENABLED: 0
          GO111MODULE: on

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset for Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./github-markdown-stars-updater-linux-amd64
          asset_name: github-markdown-stars-updater-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset for Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./github-markdown-stars-updater-windows-amd64.exe
          asset_name: github-markdown-stars-updater-windows-amd64.exe
          asset_content_type: application/octet-stream
      
      - name: Upload Release Asset for MacOS (AMD64)
        id: upload-release-asset-macos-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./github-markdown-stars-updater-darwin-amd64
          asset_name: github-markdown-stars-updater-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset for MacOS (ARM64)
        id: upload-release-asset-macos-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./github-markdown-stars-updater-darwin-arm64
          asset_name: github-markdown-stars-updater-darwin-arm64
          asset_content_type: application/octet-stream